# Generated by Django 5.1.4 on 2025-01-10 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('desc', models.CharField(max_length=300, verbose_name='Course Description')),
                ('detail', models.TextField(verbose_name='Course Details')),
                ('degree', models.CharField(choices=[('primary', 'Primary'), ('middle', 'Middle'), ('high', 'High')], max_length=10)),
                ('learn_times', models.IntegerField(default=0, verbose_name='Learning Time (minutes)')),
                ('students', models.IntegerField(default=0, verbose_name='Number of Students')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Number of Favorites')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='Cover Image')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of Clicks')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Course',
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Resource Name')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='Download Link')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Resource',
                'verbose_name_plural': 'Course Resource',
                'db_table': 'CourseResource',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lesson Name')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lesson',
                'db_table': 'Lesson',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Video Name')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
                'db_table': 'Video',
            },
        ),
    ]
