# Generated by Django 5.1.4 on 2025-01-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='courseresource',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lesson',
            table=None,
        ),
        migrations.AlterModelTable(
            name='video',
            table=None,
        ),
    ]
