# Generated by Django 5.1.4 on 2025-01-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_table_alter_courseresource_table_and_more'),
        ('orgnization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgnization.courseorg', verbose_name='Organization'),
        ),
    ]
