# Generated by Django 5.1.4 on 2025-01-10 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='User Name')),
                ('mobile', models.CharField(max_length=11, verbose_name='Mobile Number')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Consultation',
                'verbose_name_plural': 'User Consultation',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='User ID')),
                ('message', models.CharField(max_length=500, verbose_name='Message Content')),
                ('has_read', models.BooleanField(default=False, verbose_name='Read Status')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Message',
                'verbose_name_plural': 'User Message',
            },
        ),
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='Comments')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Course Comments',
                'verbose_name_plural': 'Course Comments',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Course',
                'verbose_name_plural': 'User Course',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='Data ID')),
                ('fav_type', models.IntegerField(choices=[(1, 'Course'), (2, 'Course Organization'), (3, 'Teacher')], default=1, verbose_name='Favorite Type')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': 'User Favorite',
            },
        ),
    ]
