# Generated by Django 5.1.4 on 2025-01-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='Banner Image')),
                ('url', models.URLField(verbose_name='URL')),
                ('index', models.IntegerField(default=100, verbose_name='Index')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'db_table': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Verification Code')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('send_type', models.CharField(choices=[('register', 'Register'), ('forget', 'Forget Password'), ('update', 'Update Email')], max_length=20)),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='Send Time')),
            ],
            options={
                'verbose_name': 'Email Verification Code',
                'verbose_name_plural': 'Email Verification Code',
                'db_table': 'EmailVerifyRecord',
            },
        ),
    ]
