# Generated by Django 5.1.4 on 2025-01-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table=None,
        ),
        migrations.AlterModelTable(
            name='emailverifyrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
